name: 'Setup Dotenvx'
description: 'Setup dotenvx by installing, downloading, and adding it to the path'
runs:
  using: 'composite'
  steps:
    - name: Install dotenvx
      run: |
        curl --proto '=https' --tlsv1.2 -LsSf https://github.com/linux-china/dotenvx-rs/releases/download/v0.4.11/dotenvx-rs-installer.sh | bash
      shell: bash
